### PR TITLE
Use CMake build system, rename native methods

### PR DESCRIPTION
**Pull request by hf**
@proxain has forked leveldb-android and done an amazing job at switching to CMake as the NDK build system. This will make leveldb-android more portable. 

I would like to incorporate these changes into the original repository. @proxain let me know if this is *not* OK with you, I will wait for about a week.

In order not to break backward compatibility, the minor version will probably be bumped.

### CODE REVIEW

**Comment by proxain** [comment]
Hi @hf I'm OK with that, and will be glad to contribute to your project.

**Comment by hf** [comment]
@proxain A very late reply. I'm unable to maintain this repo properly and would you like to take it over?

**Comment by proxain** [comment]
Oh, I also didn't work on this from a long time, but it nice code base and I will try to maintain it when I have time for this. Thank you.

**Comment by hf** [comment]
I'll add you a contributor then!

**Pull request closed without merging**
